### ISSUE TITLE
[OLD]  2.1 Collected data preprocessing 

### ISSUE THREAD

**Issue by SergejsKopils** [NataKrj/AI-project-2024#23]
2.1 Collected data preprocessing – converting text into a clean sequence of keywords, ready for vectorization.

**Comment by DianaStudent** [comment]
Collected data preprocessing included transforming data from xlsx to csv format. As well for each step was taken only small data samples for time saving purposes because original data have ~300000 rows.

**Comment by DianaStudent** [comment]
The solution concept was changed, so text transforming in vector data and clustering wasn’t conducted. Based on changes in solution concept, this step wasn’t included in the development process. The new solution tasks are - https://github.com/NataKrj/AI-project-2024/milestone/9
