### ISSUE TITLE
3.1 Building and training a model (Optional)

### ISSUE THREAD

**Issue by SergejsKopils** [NataKrj/AI-project-2024#24]
3.1 Building and training a model that will automatically identify risky customers based collected data – will be used one of these models: Logistic regression, random forest or gradient boosting (XGBoost). Clusters will be used as a labelled data, data will be split into training (80%) and testing (20%) datasets.

**Comment by AgiFers** [comment]
Based on previous classification results this step could improve current results analyzing domains (sources).
