### ISSUE TITLE
4.1 Evaluation metrics (Precision, Recall, F1-score)  (Optional)

### ISSUE THREAD

**Issue by SergejsKopils** [NataKrj/AI-project-2024#25]
4.1 Evaluation metrics (Precision, Recall, F1-score) will be used for a comprehensive assessment of the model, for model accuracy evaluation.

**Comment by AgiFers** [comment]
Based on previous classification results this step could improve current results analyzing domains (sources).

**Comment by NataKrj** [comment]
Based on previous classification results this step could improve current results analyzing domains (sources).

**Comment by NataKrj** [comment]
Based on previous classification results this step could improve current results analyzing domains (sources).
