### ISSUE TITLE
4.2 Reconfiguring model based on the evaluation results (Optional)

### ISSUE THREAD

**Issue by SergejsKopils** [NataKrj/AI-project-2024#26]
4.2 Model can be reconfigured based on the evaluation results

**Comment by AgiFers** [comment]
Based on previous classification results this step could improve current results analyzing domains (sources).

**Comment by NataKrj** [comment]
Based on previous classification results this step could improve current results analyzing domains (sources).

**Comment by NataKrj** [comment]
Based on previous classification results this step could improve current results analyzing domains (sources).
