### ISSUE TITLE
[OLD] 2.2 Converting Text to Vector data

### ISSUE THREAD

**Issue by SergejsKopils** [NataKrj/AI-project-2024#32]
2.2 Converting Text to Vector data – converting data into a numerical representation using TF-IDF, Word2Vec or GloVe so that clustering algorithms can process them.

**Comment by AgiFers** [comment]
We used classification and NLP anaylsis.

**Comment by DianaStudent** [comment]
The solution concept was changed, so text transforming in vector data and clustering wasn’t conducted. Based on changes in solution concept, this step wasn’t included in the development process. The new solution tasks are - https://github.com/NataKrj/AI-project-2024/milestone/9
