### ISSUE TITLE
[OLD] 2.3 Clustering using K-means or DBSCAN algorithms

### ISSUE THREAD

**Issue by SergejsKopils** [NataKrj/AI-project-2024#33]
2.3 Clustering using K-means or DBSCAN algorithms

**Comment by AgiFers** [comment]
Clustering using K-means or DBSCAN algorithms changed to Classification as a method.

**Comment by DianaStudent** [comment]
The solution concept was changed, so text transforming in vector data and clustering wasn’t conducted. Based on changes in solution concept, this step wasn’t included in the development process. The new solution tasks are - https://github.com/NataKrj/AI-project-2024/milestone/9
