### ISSUE TITLE
[OLD] 2.4 Analysis and cluster interpretation

### ISSUE THREAD

**Issue by SergejsKopils** [NataKrj/AI-project-2024#34]
2.4 Analysis and cluster interpretation - to determine which groups of articles may be associated with risk. Cluster interpretation can be conducted by analysis of keywords and topics in each cluster, manual verification of articles and assignment of risk levels.

**Comment by AgiFers** [comment]
Analysis and cluster interpretation changed to Analysis of the classification and interpretation

**Comment by DianaStudent** [comment]
The solution concept was changed, so text transforming in vector data and clustering wasn’t conducted. Based on changes in solution concept, this step wasn’t included in the development process. The new solution tasks are - https://github.com/NataKrj/AI-project-2024/milestone/9
