### ISSUE TITLE
2.5 Classification evaluation and improvement

### ISSUE THREAD

**Issue by SergejsKopils** [NataKrj/AI-project-2024#35]
2.5 Cluster evaluation and improvement – that includes checking the clustering results and anomalies, number of clusters increasing or decreasing will be performed if necessary.

**Comment by AgiFers** [comment]
Cluster evaluation and improvement changed to Classification evaluation and improvement

**Comment by DianaStudent** [comment]
The solution concept was changed, so text transforming in vector data and clustering wasn’t conducted. Based on changes in solution concept, this step wasn’t included in the development process. The new solution tasks are - https://github.com/NataKrj/AI-project-2024/milestone/9
