### ISSUE TITLE
[OLD] 2.6 Final Evaluation and Report 

### ISSUE THREAD

**Issue by SergejsKopils** [NataKrj/AI-project-2024#36]
2.6 Final Evaluation and Report - after clustering and interpreting the clusters, a descriptive report should be prepared with describing of each cluster and its risk level (high, medium, low).

**Comment by AgiFers** [comment]
The results for each Step of classification with score and risk level assigned.

**Comment by DianaStudent** [comment]
The solution concept was changed, so text transforming in vector data and clustering wasn’t conducted. Based on changes in solution concept, this step wasn’t included in the development process. The new solution tasks are - https://github.com/NataKrj/AI-project-2024/milestone/9
