### ISSUE TITLE
[OLD] 2.7 Assigning a risk level to each client 

### ISSUE THREAD

**Issue by SergejsKopils** [NataKrj/AI-project-2024#37]
2.7 Assigning a risk level to each client - identifying the appropriate risk level to each client based on client association with clusters.

**Comment by DianaStudent** [comment]
The solution concept was changed, so text transforming in vector data and clustering wasn’t conducted. Based on changes in solution concept, this step wasn’t included in the development process. The new solution tasks are - https://github.com/NataKrj/AI-project-2024/milestone/9
