### ISSUE TITLE
5.1 Model will be applied to a new data

### ISSUE THREAD

**Issue by SergejsKopils** [NataKrj/AI-project-2024#39]
5.1 Model will be applied to a new data – new articles mentioning clients, as a result of modelling will be a report for each client, that includes - Number and content of articles associated with the client, risk level (high, medium, low).

**Comment by AgiFers** [comment]
Based on previous classification results this step could improve current results analyzing domains (sources).

**Comment by NataKrj** [comment]
Based on previous classification results this step could improve current results analyzing domains (sources).
